---
- name: first playbook
  hosts: all
  become: true

  tasks:
    - name: install required packages for WordPress
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - wget
          - unzip
        state: present
        update_cache: yes

    - name: download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz
        mode: '0644'

    - name: extract WordPress files
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html
        remote_src: yes

    - name: set file ownership
      file:
        path: /var/www/html/wordpress
        recurse: yes
        owner: www-data
        group: www-data
