---
- name: Setup WordPress server
  hosts: wordpress
  become: true
  tasks:
    - name: Install WordPress prerequisites
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - wget
          - unzip
        state: present
        update_cache: yes

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz
        mode: '0644'

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html
        remote_src: yes

    - name: Move WordPress files to web root
      command: mv /var/www/html/wordpress/* /var/www/html/
      args:
        removes: /var/www/html/index.php

    - name: Set ownership
      file:
        path: /var/www/html
        recurse: yes
        owner: www-data
        group: www-data

- name: Setup Apache HTTP server
  hosts: http
  become: true
  tasks:
    - name: Install Apache server only
      apt:
        name: apache2
        state: present
        update_cache: yes
